package com.transbank.webpay.wswebpay.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-07-18T15:17:03.148-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://service.wswebpay.webpay.transbank.com/", name = "WSCompleteWebpayService")
@XmlSeeAlso({ObjectFactory.class})
public interface WSCompleteWebpayService {

    @WebMethod
    @RequestWrapper(localName = "initCompleteTransaction", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.InitCompleteTransaction")
    @ResponseWrapper(localName = "initCompleteTransactionResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.InitCompleteTransactionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpay.wswebpay.service.WsCompleteInitTransactionOutput initCompleteTransaction(
        @WebParam(name = "wsCompleteInitTransactionInput", targetNamespace = "")
        com.transbank.webpay.wswebpay.service.WsCompleteInitTransactionInput wsCompleteInitTransactionInput
    );

    @WebMethod
    @RequestWrapper(localName = "authorize", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.AuthorizeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpay.wswebpay.service.WsCompleteAuthorizeOutput authorize(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "paymentTypeList", targetNamespace = "")
        java.util.List<com.transbank.webpay.wswebpay.service.WsCompletePaymentTypeInput> paymentTypeList
    );

    @WebMethod
    @RequestWrapper(localName = "acknowledgeCompleteTransaction", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.AcknowledgeCompleteTransaction")
    @ResponseWrapper(localName = "acknowledgeCompleteTransactionResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.AcknowledgeCompleteTransactionResponse")
    public void acknowledgeCompleteTransaction(
        @WebParam(name = "tokenInput", targetNamespace = "")
        java.lang.String tokenInput
    );

    @WebMethod
    @RequestWrapper(localName = "queryShare", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.QueryShare")
    @ResponseWrapper(localName = "queryShareResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.QueryShareResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpay.wswebpay.service.WsCompleteQuerySharesOutput queryShare(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "buyOrder", targetNamespace = "")
        java.lang.String buyOrder,
        @WebParam(name = "shareNumber", targetNamespace = "")
        int shareNumber
    );
}
