
package com.transbank.webpay.wswebpay.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCommerceIntegrationServiceImplService", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", wsdlLocation = "file:/C:/SVN/Integradores%20WEWBPAY/01%20-%20Integradores%20WebPay/03%20EJECUCION/FUENTES/JAVA/04%20-%20Version%20completa%20entregable/webpay-sdk-java-1.1/libwebpay/src/wsdl/integracion/nullify.wsdl")
public class WSCommerceIntegrationServiceImplService
    extends Service
{

    private final static URL WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_QNAME = new QName("http://service.wswebpay.webpay.transbank.com/", "WSCommerceIntegrationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/SVN/Integradores%20WEWBPAY/01%20-%20Integradores%20WebPay/03%20EJECUCION/FUENTES/JAVA/04%20-%20Version%20completa%20entregable/webpay-sdk-java-1.1/libwebpay/src/wsdl/integracion/nullify.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WSCommerceIntegrationServiceImplService() {
        super(__getWsdlLocation(), WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_QNAME);
    }

    public WSCommerceIntegrationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSCommerceIntegrationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_QNAME);
    }

    public WSCommerceIntegrationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSCommerceIntegrationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCommerceIntegrationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCommerceIntegrationService
     */
    @WebEndpoint(name = "WSCommerceIntegrationServiceImplPort")
    public WSCommerceIntegrationService getWSCommerceIntegrationServiceImplPort() {
        return super.getPort(new QName("http://service.wswebpay.webpay.transbank.com/", "WSCommerceIntegrationServiceImplPort"), WSCommerceIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCommerceIntegrationService
     */
    @WebEndpoint(name = "WSCommerceIntegrationServiceImplPort")
    public WSCommerceIntegrationService getWSCommerceIntegrationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wswebpay.webpay.transbank.com/", "WSCommerceIntegrationServiceImplPort"), WSCommerceIntegrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WSCOMMERCEINTEGRATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
