package com.transbank.webpay.wswebpay.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-07-18T15:17:03.193-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "WSCompleteWebpayServiceImplService", 
                  wsdlLocation = "file:complete.wsdl",
                  targetNamespace = "http://service.wswebpay.webpay.transbank.com/") 
public class WSCompleteWebpayServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.wswebpay.webpay.transbank.com/", "WSCompleteWebpayServiceImplService");
    public final static QName WSCompleteWebpayServiceImplPort = new QName("http://service.wswebpay.webpay.transbank.com/", "WSCompleteWebpayServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:complete.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSCompleteWebpayServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:complete.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSCompleteWebpayServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSCompleteWebpayServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCompleteWebpayServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSCompleteWebpayServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSCompleteWebpayServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSCompleteWebpayServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WSCompleteWebpayService
     */
    @WebEndpoint(name = "WSCompleteWebpayServiceImplPort")
    public WSCompleteWebpayService getWSCompleteWebpayServiceImplPort() {
        return super.getPort(WSCompleteWebpayServiceImplPort, WSCompleteWebpayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCompleteWebpayService
     */
    @WebEndpoint(name = "WSCompleteWebpayServiceImplPort")
    public WSCompleteWebpayService getWSCompleteWebpayServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WSCompleteWebpayServiceImplPort, WSCompleteWebpayService.class, features);
    }

}
