
package com.transbank.webpay.wswebpay.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCommerceIntegrationService", targetNamespace = "http://service.wswebpay.webpay.transbank.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCommerceIntegrationService {


    /**
     * 
     * @param nullificationInput
     * @return
     *     returns com.transbank.webpay.wswebpay.service.NullificationOutput
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nullify", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.Nullify")
    @ResponseWrapper(localName = "nullifyResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.NullifyResponse")
    public NullificationOutput nullify(
        @WebParam(name = "nullificationInput", targetNamespace = "")
        NullificationInput nullificationInput);

    /**
     * 
     * @param captureInput
     * @return
     *     returns com.transbank.webpay.wswebpay.service.CaptureOutput
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "capture", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.Capture")
    @ResponseWrapper(localName = "captureResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.CaptureResponse")
    public CaptureOutput capture(
        @WebParam(name = "captureInput", targetNamespace = "")
        CaptureInput captureInput);

}
