package com.transbank.webpay.wswebpay.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-24T13:06:59.961-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "WSWebpayServiceImplService", 
                  wsdlLocation = "file:normal.wsdl",
                  targetNamespace = "http://service.wswebpay.webpay.transbank.com/") 
public class WSWebpayServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.wswebpay.webpay.transbank.com/", "WSWebpayServiceImplService");
    public final static QName WSWebpayServiceImplPort = new QName("http://service.wswebpay.webpay.transbank.com/", "WSWebpayServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:normal.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSWebpayServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:normal.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSWebpayServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSWebpayServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSWebpayServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSWebpayServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSWebpayServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSWebpayServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WSWebpayService
     */
    @WebEndpoint(name = "WSWebpayServiceImplPort")
    public WSWebpayService getWSWebpayServiceImplPort() {
        return super.getPort(WSWebpayServiceImplPort, WSWebpayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSWebpayService
     */
    @WebEndpoint(name = "WSWebpayServiceImplPort")
    public WSWebpayService getWSWebpayServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WSWebpayServiceImplPort, WSWebpayService.class, features);
    }

}
