package com.transbank.webpay.wswebpay.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-24T13:06:59.913-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://service.wswebpay.webpay.transbank.com/", name = "WSWebpayService")
@XmlSeeAlso({ObjectFactory.class})
public interface WSWebpayService {

    @WebMethod
    @RequestWrapper(localName = "acknowledgeTransaction", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.AcknowledgeTransaction")
    @ResponseWrapper(localName = "acknowledgeTransactionResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.AcknowledgeTransactionResponse")
    public void acknowledgeTransaction(
        @WebParam(name = "tokenInput", targetNamespace = "")
        java.lang.String tokenInput
    );

    @WebMethod
    @RequestWrapper(localName = "getTransactionResult", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.GetTransactionResult")
    @ResponseWrapper(localName = "getTransactionResultResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.GetTransactionResultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpay.wswebpay.service.TransactionResultOutput getTransactionResult(
        @WebParam(name = "tokenInput", targetNamespace = "")
        java.lang.String tokenInput
    );

    @WebMethod
    @RequestWrapper(localName = "initTransaction", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.InitTransaction")
    @ResponseWrapper(localName = "initTransactionResponse", targetNamespace = "http://service.wswebpay.webpay.transbank.com/", className = "com.transbank.webpay.wswebpay.service.InitTransactionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpay.wswebpay.service.WsInitTransactionOutput initTransaction(
        @WebParam(name = "wsInitTransactionInput", targetNamespace = "")
        com.transbank.webpay.wswebpay.service.WsInitTransactionInput wsInitTransactionInput
    );
}
