package com.transbank.webpayserver.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-23T16:00:36.735-03:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://webservices.webpayserver.transbank.com/", name = "OneClickPaymentService")
@XmlSeeAlso({ObjectFactory.class})
public interface OneClickPaymentService {

    @WebMethod
    @RequestWrapper(localName = "finishInscription", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.FinishInscription")
    @ResponseWrapper(localName = "finishInscriptionResponse", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.FinishInscriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpayserver.webservices.OneClickFinishInscriptionOutput finishInscription(
        @WebParam(name = "arg0", targetNamespace = "")
        com.transbank.webpayserver.webservices.OneClickFinishInscriptionInput arg0
    );

    @WebMethod
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.RemoveUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.transbank.webpayserver.webservices.OneClickRemoveUserInput arg0
    );

    @WebMethod
    @RequestWrapper(localName = "initInscription", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.InitInscription")
    @ResponseWrapper(localName = "initInscriptionResponse", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.InitInscriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpayserver.webservices.OneClickInscriptionOutput initInscription(
        @WebParam(name = "arg0", targetNamespace = "")
        com.transbank.webpayserver.webservices.OneClickInscriptionInput arg0
    );

    @WebMethod
    @RequestWrapper(localName = "codeReverseOneClick", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.CodeReverseOneClick")
    @ResponseWrapper(localName = "codeReverseOneClickResponse", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.CodeReverseOneClickResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpayserver.webservices.OneClickReverseOutput codeReverseOneClick(
        @WebParam(name = "arg0", targetNamespace = "")
        com.transbank.webpayserver.webservices.OneClickReverseInput arg0
    );

    @WebMethod
    @RequestWrapper(localName = "reverse", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.Reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.ReverseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean reverse(
        @WebParam(name = "arg0", targetNamespace = "")
        com.transbank.webpayserver.webservices.OneClickReverseInput arg0
    );

    @WebMethod
    @RequestWrapper(localName = "authorize", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://webservices.webpayserver.transbank.com/", className = "com.transbank.webpayserver.webservices.AuthorizeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.transbank.webpayserver.webservices.OneClickPayOutput authorize(
        @WebParam(name = "arg0", targetNamespace = "")
        com.transbank.webpayserver.webservices.OneClickPayInput arg0
    );
}
